# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
### Get Example
GET http://localhost:3010/
Content-Type: application/json

### Store Participant
POST http://localhost:3010/participant
Content-Type: application/json

{
  "id": "{{$uuid}}",
  "name": "sally",
  "isActive": true,
  "description": "A MJL person.",
  "createdDate": "{{$timestamp}}",
  "createdBy": "api"
}

### Get Participant
GET http://localhost:3010/participant/sally
Content-Type: application/json

